version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
  disable:
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
